version: '3'
services:
  mysql:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mediawiki

  wiki:
    image: ghcr.io/radiorabe/mediawiki:latest
    build: ./wiki
    ports:
      - "8081:80"
    environment:
      MW_WG_SERVER: ~
      MW_WG_DBUSER: root
      MW_WG_DBPASS: secret
      MW_WG_LANGUAGECODE: en
      MW_WG_RAWHTML: 'false'
      MW_WG_SECRET: ~
    volumes:
      - ./images:/var/www/html/images

  backup:
    image: schnitzler/mysqldump
    volumes:
      # backup script to use
      - ./backup/backup.sh:/etc/periodic/daily/backup:ro
      # volume for backing up files
      - ./images:/images:ro
      # mount backups
      - ./backup/:/backup
    command: ["-l", "8", "-d", "8"]
    environment:
      BACKUP_RETENTION: 14
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: mediawiki
