---
general:
  vulnerabilities:
  # CVE-2021-29921: Python before 3.9.5
  # at the time of writing this was not patched in upstream Debian,
  # Python isn't in the critical path of this images runtime features
  # so we allowlist this python update related CVE for now.
  # https://bugs.python.org/issue36384#msg392423
  - CVE-2021-29921
  # CVE-2021-22945: libcurl MQTT data sending
  # Mediawiki does not have any MQTT-via-libcurl features.
  - CVE-2021-22945
  # CVE-2021-22946: TLS bypass for IMAP, POP3 or FTP
  # RaBe Wiki does not use IMAP, POP3 or FTP.
  - CVE-2021-22946
  # CVE-2020-23109: Buffer overflow vulnerability in libheif1
  # RaBe Wiki does not support uploading HEIF files.
  - CVE-2020-23109
  # CVE-2021-42739: Buffer overflow in kernel firewire driver
  # We don't care about kernel modules in containers.
  - CVE-2021-42739
  # CVE-2021-41864: Integer overflow in eBPF kernel driver
  # We don't care about kernel modules in containers.
  - CVE-2021-41864
  # CVE-2021-3752: Use-after-free in kernels bluetooth subsystem
  # We don't care about kernel modules in containers.
  - CVE-2021-3752
  # CVE-2021-20241: division by zero in ImageMagick
  # Ignored by Debian Security Team: https://tracker.debian.org/pkg/imagemagick
  - CVE-2021-20241
  # CVE-2021-20243: division by zero in ImageMagick
  # Ignored by Debian Security Team: https://tracker.debian.org/pkg/imagemagick
  - CVE-2021-20243
  # CVE-2021-20244: division by zero in ImageMagick
  # Ignored by Debian Security Team: https://tracker.debian.org/pkg/imagemagick
  - CVE-2021-20244
  # CVE-2021-20245: division by zero in ImageMagick
  # Ignored by Debian Security Team: https://tracker.debian.org/pkg/imagemagick
  - CVE-2021-20245
  # CVE-2021-20246: division by zero in ImageMagick
  # Ignored by Debian Security Team: https://tracker.debian.org/pkg/imagemagick
  - CVE-2021-20246
  # CVE-2021-20309: division by zero in ImageMagick
  # Ignored by Debian Security Team: https://tracker.debian.org/pkg/imagemagick
  - CVE-2021-20309
  # CVE-2021-20312: integer overflow in ImageMagick
  # Ignored by Debian Security Team: https://tracker.debian.org/pkg/imagemagick
  - CVE-2021-20312
  bestPracticeViolations:
  # CIS-DI-0001: Last user should not be root
  # We build on an upstream Apache image as supported by Mediawiki.
  # In this scenario Apache HTTPD drops privileges for us. Making
  # httpd run as non root is complicated due to a variety of factors.
  - CIS-DI-0001
  # CIS-DI-0005: Enable Content trust for Docker
  # We do't currently have a strategy implemented to support content
  # trust.
  - CIS-DI-0005
