name: Scheduled tasks

on:
  schedule:
    - cron:  '13 12 * * *'
  workflow_dispatch:

jobs:
  call-workflow:
    uses: radiorabe/actions/.github/workflows/schedule-trivy.yaml@953c51da7e4c2c681f15c70513cb803c8fa461cc # v0.44.3
    with:
      image-ref: 'ghcr.io/radiorabe/mediawiki:latest'
