name: Scheduled tasks

on:
  schedule:
    - cron:  '13 12 * * *'
  workflow_dispatch:

jobs:
  call-workflow:
    uses: radiorabe/actions/.github/workflows/schedule-trivy.yaml@479996126a091287dc3fd349786f6f8a6dd1b23c # v0.42.0
    with:
      image-ref: 'ghcr.io/radiorabe/mediawiki:latest'
