name: Run semantic-release

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run go-semantic-release
        id: semrel
        uses: go-semantic-release/action@v1
        with:
          github-token: ${{ secrets.RABE_ITREAKTION_GITHUB_TOKEN }}
          allow-initial-development-versions: true
        if: ${{ github.ref == 'refs/heads/main' }}
