name: Run semantic-release

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Run go-semantic-release
        id: semrel
        uses: go-semantic-release/action@2e9dc4247a6004f8377781bef4cb9dad273a741f # v1.24.1
        with:
          github-token: ${{ secrets.RABE_ITREAKTION_GITHUB_TOKEN }}
          allow-initial-development-versions: true
        if: ${{ github.ref == 'refs/heads/main' }}
